; Stream Activity Bot - real Windows installer (Inno Setup 6).
;
; The installer packs the COMPLETE PyInstaller ONEDIR build (EXE + python312.dll + PySide6 +
; shiboken6 + Qt DLLs + .pyd files ...).  Nothing is extracted by a PyInstaller bootloader, so the
; old "Failed to extract shiboken6.abi3.dll / python312.dll" errors cannot happen.
;
; Built in CI with:  ISCC.exe /DAppVersion=20.0 /DSourceDir=..\dist\Stream_Activity_Bot StreamActivityBot.iss
; Output: installer_output\Stream_Activity_Bot_Setup.exe   (ONE file)

#ifndef AppVersion
  #define AppVersion "0.0"
#endif
#ifndef SourceDir
  #define SourceDir "..\dist\Stream_Activity_Bot"
#endif
#define AppName "Stream Activity Bot"
#define AppExe  "Stream_Activity_Bot.exe"

[Setup]
; Fixed AppId = stable identity for upgrades and for the uninstall entry. Never change it.
AppId={{B7C3E6B8-5E0F-4A63-9C3B-6C1F1D5A0B21}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppName}
VersionInfoVersion={#AppVersion}.0.0
VersionInfoProductName={#AppName}
VersionInfoDescription={#AppName} Setup
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
; Per-user install by default (no admin prompt); the user can still choose "all users".
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
OutputDir=..\installer_output
OutputBaseFilename=Stream_Activity_Bot_Setup
SetupIconFile=..\app.ico
UninstallDisplayIcon={app}\{#AppExe}
UninstallDisplayName={#AppName}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
WizardSizePercent=110,110
; Branded artwork (generated by scripts/make_installer_art.py): dark side panel + app icon.
; Several sizes are listed so the images stay sharp at 100% / 150% / 200% Windows scaling.
WizardImageFile=wizard_side.bmp,wizard_side_150.bmp,wizard_side_200.bmp
WizardSmallImageFile=wizard_small.bmp,wizard_small_150.bmp,wizard_small_200.bmp
WizardImageBackColor=$0D0D06
WizardImageStretch=no
CloseApplications=yes
RestartApplications=no

[Languages]
; Bulgarian ships with Inno Setup 6; fall back to English if a build machine lacks the file.
#if FileExists(CompilerPath + "Languages\Bulgarian.isl")
Name: "bulgarian"; MessagesFile: "compiler:Languages\Bulgarian.isl"
#else
Name: "english"; MessagesFile: "compiler:Default.isl"
#endif

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
; The whole ONEDIR folder, exactly as PyInstaller produced it.
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExe}"
Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExe}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExe}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Remove the program folder completely (runtime dependencies, caches).
; User settings/data live in %APPDATA%\Stream Activity Bot and are intentionally kept.
Type: filesandordirs; Name: "{app}"
